### ISSUE TITLE
Better Handling of Null Results

### ISSUE THREAD

**Issue by ardichoke** [knuedge/lita-puppet#16]
Currently, when puppetdb returns a null result, the handler crashes. In my particular case, this happens any time I query a role or profile (as we don't currently use roles or profiles).

> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-puppet-2.1.0/lib/utils/lita_puppet/puppetdb.rb:70:in `[]'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-puppet-2.1.0/lib/utils/lita_puppet/puppetdb.rb:70:in `node_roles_and_profiles'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-puppet-2.1.0/lib/lita/handlers/puppet.rb:112:in `node_profiles'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/callback.rb:31:in `public_send'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/callback.rb:31:in `call'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:97:in `dispatch_to_route'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:82:in `block in dispatch'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:72:in `map'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:72:in `dispatch'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/robot.rb:69:in `block in receive'
> /home/lita/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/set.rb:324:in `each_key'
> /home/lita/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/set.rb:324:in `each'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/robot.rb:66:in `map'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/robot.rb:66:in `receive'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-slack-1.8.0/lib/lita/adapters/slack/message_handler.rb:122:in `dispatch_message'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-slack-1.8.0/lib/lita/adapters/slack/message_handler.rb:159:in `handle_message'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-slack-1.8.0/lib/lita/adapters/slack/message_handler.rb:18:in `handle'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-slack-1.8.0/lib/lita/adapters/slack/rtm_connection.rb:100:in `block in receive_message'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-slack-1.8.0/lib/lita/adapters/slack/event_loop.rb:10:in `block in defer'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/eventmachine-1.2.3/lib/eventmachine.rb:1076:in `block in spawn_threadpool'

Results from puppetdb should be checked for a null result and an appropriate message should be returned, instead of crashing silently in the background.

**Comment by jgnagy** [comment]
Which puppet and puppetdb versions are you running?

**Comment by ardichoke** [comment]
puppet 3.8.7 & puppetdb 2.3.8 (using the v4 API, even though it's technically experimental in that version).

I want to get our setup to a modern version of puppet, but that's going to take a lot of time that I don't have right now, as we have a lot of custom code that is going to need testing and probably changes.

**Comment by dschaaff** [comment]
The pull request I just submitted might address your issue. If there no tags returned from puppetdb matching roles or profiles it returns an empty array. We now correctly handle this case. 

Is that the full stack trace above?

**Comment by jgnagy** [comment]
Re-opening until we have confirmation that the issue is resolved.

**Comment by ardichoke** [comment]
Sorry, it seems I missed the first couple lines. This is the full output from lita:

> [2017-04-14 14:51:46 UTC] ERROR: Lita::Handlers::Puppet crashed. The exception was:
> no implicit conversion of String into Integer
> Full backtrace:
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-puppet-2.1.0/lib/utils/lita_puppet/puppetdb.rb:70:in `[]'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-puppet-2.1.0/lib/utils/lita_puppet/puppetdb.rb:70:in `node_roles_and_profiles'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-puppet-2.1.0/lib/lita/handlers/puppet.rb:112:in `node_profiles'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/callback.rb:31:in `public_send'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/callback.rb:31:in `call'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:97:in `dispatch_to_route'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:82:in `block in dispatch'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:72:in `map'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:72:in `dispatch'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/robot.rb:69:in `block in receive'
> /home/lita/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/set.rb:324:in `each_key'
> /home/lita/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/set.rb:324:in `each'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/robot.rb:66:in `map'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-4.7.1/lib/lita/robot.rb:66:in `receive'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-slack-1.8.0/lib/lita/adapters/slack/message_handler.rb:122:in `dispatch_message'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-slack-1.8.0/lib/lita/adapters/slack/message_handler.rb:159:in `handle_message'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-slack-1.8.0/lib/lita/adapters/slack/message_handler.rb:18:in `handle'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-slack-1.8.0/lib/lita/adapters/slack/rtm_connection.rb:100:in `block in receive_message'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/lita-slack-1.8.0/lib/lita/adapters/slack/event_loop.rb:10:in `block in defer'
> /home/lita/.rvm/gems/ruby-2.4.1/gems/eventmachine-1.2.3/lib/eventmachine.rb:1076:in `block in spawn_threadpool'

**Comment by dschaaff** [comment]
I just pushed the new version. Give it a try when you get a chance and let us know.

**Comment by ardichoke** [comment]
I'm afraid not, it still throws the same stack trace for me after update.

**Comment by dschaaff** [comment]
We'll need some more info to troubleshoot further then as we can't reproduce the issue right now.

do you get results for the other puppetdb queries available in the plugin?
can you get results for a manual query of the catalogs puppetdb endpoint for the node that you are trying to query?

**Comment by ardichoke** [comment]
Yes, the other queries seem to work as expected so far. When I was using the v3 API, there was another one that threw a stack trace, but I can't recall what it was and switching to the v4 API resolved that particular issue (roles and profiles stack traced on both versions).

I will attempt to do a manual query and provide the results... though it might take me a bit to figure out how. I haven't really worked with puppetdb directly before.

**Comment by ardichoke** [comment]
After some digging around, I seem to have found the problem. In the version of puppetdb I'm using, the catalog data is not in the structure that you're expecting. Instead of 

`'resources': {'data': [ ... ] } }`

it is structured as such:

`'resources': [...]`

so, on puppetdb.rb doing `d['resources']['data'].each` fails as 'data' is not an integer when `d['resources']` is an array.

I managed to patch it to at least not dump core on this issue. I'm unsure if it returns appropriate roles/profile data though, since I don't actually use roles or profiles at the moment. I'll submit a PR shortly.
